sudo: required
dist: trusty

language: csharp
mono: none
dotnet: 2.1.300

env:
  global:
  - DOTNET_CLI_TELEMETRY_OPTOUT=1
  - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1

before_install:
- npm install --save-dev coveralls
- # git fetch --unshallow # Travis always does a shallow clone, but GitVersion needs the full history including branches and tags

script:
- dotnet sln Z85e.sln remove src/Z85e.Benchmarks/Z85e.Benchmarks.csproj
- dotnet restore
- dotnet msbuild /p:configuration=Release 
- chmod +x .scripts/TestCoverage.sh && ./.scripts/TestCoverage.sh 

cache:
  directories:
    - $HOME/.nuget/packages