image:
- Ubuntu
- Visual Studio 2017

configuration: Debug	
#platform: Any CPU

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  github_oauth_token:
    secure: H1vW5fnfAOt5/c5f1qnaatUjFVAPc2oZnxDBFutJZL58LxAyJNRLtfIBrcHnSg8y
  COVERALLS_REPO_TOKEN:
    secure: rhtibrJj8xGqbiy5Fyx7T8Iopw3wpzgrS2yKTkffoF3Ps78M1rVNWl36ZIhOU0BM
  
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '%GitVersion_NuGetVersion%'
  package_version: '%GitVersion_NuGetVersion%'
  #version: '{version}'
  #package_version: '{version}'
  # assembly_version: '{version}'
  # file_version: '{version}'
  informational_version: '%GitVersion_InformationalVersion%'

install:
# Install and run gitversion. (use param "/l console" to show debug info)
- cmd: choco install gitversion.portable -pre -y
- cmd: C:\ProgramData\chocolatey\lib\gitversion.portable\tools\gitversion.exe /output buildserver /c %APPVEYOR_REPO_COMMIT%
- sh: chmod +x .scripts/InstallGitVersion.sh && .scripts/InstallGitVersion.sh

# Install OpenCover (windows)
- cmd: choco install opencover.portable -y

# Install (latest) codecov (choco is behind of nuget) and coveralls in linux.
- cmd: nuget install Codecov -Version 1.0.5 -OutputDirectory C:\NuGetTools\
- sh: nuget install Codecov -Version 1.0.5 -OutputDirectory .scripts/NuGetTools/
- sh: npm install --save-dev coveralls

# git update submodules.
- git submodule update --init --recursive

before_build:
# Remove Benchmark project as it relies on .net framework 
- sh: dotnet sln Z85e.sln remove src/Z85e.Benchmarks/Z85e.Benchmarks.csproj
- dotnet restore

build_script:
- dotnet build

test_script:
- cmd: powershell .\.scripts\TestCoverage.ps1
- sh: chmod +x .scripts/TestCoverage.sh && .scripts/TestCoverage.sh
#
- sh: curl -s https://codecov.io/bash > codecov
- sh: chmod +x codecov
- sh: ./codecov -f "MyProject_coverage.xml"

after_test:
- ps: .scripts\pack.ps1
- cmd: powershell .scripts\Codecov.ps1

artifacts:
  - path: '**\*.nupkg'
    name: NuGet Packages

deploy:
  - provider: NuGet
    name: pre-release
    server: https://www.myget.org/F/coenm/api/v2/package
    api_key:
        secure: t8JtzPkpHidqOii+bLuSiOKgqzsdoSCBI3Sc/Uy6D9jWfxNd7zUUhhTgGHj5rpV9
    skip_symbols: true
    # symbol_server: https://www.myget.org/F/coenm/symbols/api/v2/package
    artifact: /.*\.nupkg/
    on:
        branch: /(master|release.*|develop)/	
  
  # - provider: NuGet
  #  name: production
  #  # note, the NuGet api key expires on 2018-11-09
  #  api_key:
  #      secure: QNK9GUakj8Eu2o2ljO/BlKQcOk4abyfrv0WwwGgu1iFCB034Cs3mb09lTXT0qYNM
  #  on:
  #      branch: /(master|release.*)/
       
  # - provider: NuGet
  #   name: production
  #   # note, the NuGet api key expires on 2018-11-09
  #   api_key:
  #       secure: QNK9GUakj8Eu2o2ljO/BlKQcOk4abyfrv0WwwGgu1iFCB034Cs3mb09lTXT0qYNM
  #   on:       
  #       branch: /release.*/
    # on:
    #     appveyor_repo_tag: true