image: Visual Studio 2017
configuration: Release	
#platform: Any CPU

environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  github_oauth_token:
    secure: H1vW5fnfAOt5/c5f1qnaatUjFVAPc2oZnxDBFutJZL58LxAyJNRLtfIBrcHnSg8y
  
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '%GitVersion_NuGetVersion%'
  package_version: '%GitVersion_NuGetVersion%'
  #version: '{version}'
  #package_version: '{version}'
  # assembly_version: '{version}'
  # file_version: '{version}'
  informational_version: '%GitVersion_InformationalVersion%'

install:
- choco install gitversion.portable -pre -y
- choco install opencover.portable -y
  #
  # install latest codecov (choco is behind of nuget)
- nuget install Codecov -OutputDirectory C:\NuGetTools\
- C:\ProgramData\chocolatey\lib/gitversion.portable/tools/gitversion.exe /l console /output buildserver
- git submodule update --init --recursive

before_build:
- dotnet restore

build_script:
- dotnet build

test_script:
- ps: .scripts\TestCoverage.ps1

after_test:
- ps: .scripts\pack.ps1
- ps: .scripts\Codecov.ps1

artifacts:
  - path: '**\*.nupkg'
    name: NuGet Packages

deploy:
  - provider: NuGet
    name: pre-release
    server: https://www.myget.org/F/coenm/api/v2/package
    api_key:
        secure: t8JtzPkpHidqOii+bLuSiOKgqzsdoSCBI3Sc/Uy6D9jWfxNd7zUUhhTgGHj5rpV9
    skip_symbols: true
    # symbol_server: https://www.myget.org/F/coenm/symbols/api/v2/package
    artifact: /.*\.nupkg/
    on:
        branch: /(master|release.*|develop)/	
  
  # - provider: NuGet
  #  name: production
  #  # note, the NuGet api key expires on 2018-11-09
  #  api_key:
  #      secure: QNK9GUakj8Eu2o2ljO/BlKQcOk4abyfrv0WwwGgu1iFCB034Cs3mb09lTXT0qYNM
  #  on:
  #      branch: /(master|release.*)/
       
  # - provider: NuGet
  #   name: production
  #   # note, the NuGet api key expires on 2018-11-09
  #   api_key:
  #       secure: QNK9GUakj8Eu2o2ljO/BlKQcOk4abyfrv0WwwGgu1iFCB034Cs3mb09lTXT0qYNM
  #   on:       
  #       branch: /release.*/
    # on:
    #     appveyor_repo_tag: true